image: mcr.microsoft.com/dotnet/core/sdk:3.1

build:
    only:
        - master
    artifacts:
        paths: 
            - publish/
    script:
        - dotnet publish -c Release -o publish

build-win:
    only:
        - master
    artifacts:
        paths:
            - publish/
    script:
        - dotnet publish -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained -r win-x64 -c Release -o publish

build-lin:
    only:
        - master
    artifacts:
        paths:
            - publish/
    script:
        - dotnet publish -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained -r linux-x64 -c Release -o publish
